# Generated by Django 4.2.2 on 2023-06-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianoblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpost',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
