# Generated by Django 4.2.2 on 2023-06-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianoblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='post',
        ),
    ]
