# Generated by Django 4.2.2 on 2023-06-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianoblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='content_type',
        ),
    ]
