# Generated by Django 4.2.2 on 2023-07-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianoblog', '0002_remove_imagepost_post_remove_videopost_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='image',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='videopost',
            old_name='video',
            new_name='content',
        ),
    ]
