# Generated by Django 4.2.2 on 2023-06-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianoblog', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_owner',
            new_name='owner',
        ),
    ]
