# Generated by Django 4.2.2 on 2023-06-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianoblog', '0003_imagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
