# Generated by Django 4.2.2 on 2023-07-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianoblog', '0003_rename_image_imagepost_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='content',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='videopost',
            old_name='content',
            new_name='video',
        ),
    ]
