# Generated by Django 4.2.2 on 2023-06-26 08:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianoblog', '0004_imagepost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
