# Generated by Django 4.2.2 on 2023-06-28 21:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianoblog', '0005_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dayngkoud/image/upload/v1687988552/piano_icon_pijapc.png', max_length=255, verbose_name='image'),
        ),
    ]
