# Generated by Django 4.2.2 on 2023-06-26 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pianoblog', '0005_remove_imagepost_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('imagepost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagepost_comments', to='pianoblog.imagepost')),
                ('textpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textpost_comments', to='pianoblog.textpost')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.DeleteModel(
            name='TextComment',
        ),
    ]
