# Generated by Django 4.2.2 on 2023-06-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pianoblog', '0007_videopost'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='videopost',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='videopost_comments', to='pianoblog.videopost'),
            preserve_default=False,
        ),
    ]
