# Generated by Django 4.2.2 on 2023-06-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pianoblog', '0009_imagepostcomment_textpostcomment_videopostcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepostcomment',
            name='imagepost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagepost_comments', to='pianoblog.imagepost'),
        ),
        migrations.AlterField(
            model_name='videopostcomment',
            name='videopost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videopost_comments', to='pianoblog.videopost'),
        ),
    ]
